### ISSUE TITLE
[Various > Theming] Implement unload

### ISSUE THREAD

**Issue by hyblocker** [polymod-org/polymod#1]
If I enable the themes plugin, and then disable it, the site remains themed, until a refresh.
Given the fact that toggling individual themes is instantaneous, and that themes are simply CSS, this might not be intended behavior.

**Comment by CanadaHonk** [comment]
Known, it's not implemented yet as it is an unneeded pain mostly.

**Comment by CanadaHonk** [comment]
Was done
